### ISSUE TITLE
TODO before usage

### ISSUE THREAD

**Issue by curtiswilkinson** [curtiswilkinson/reavis#1]
**Definitely**
- [ ] `include` and `exclude` options for dependency globs
- [ ] timestamp differentials to determine if a function should run
- [ ] An actual name

**Maybe**
- [ ] top level "post" and "pre" scripts 
- [ ] fix the `--project [path]` flag not working
